title: Modernist theme
description: Modernist is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist

# Site settings
description: Quickstart for Installing and Configuring ownCloud"
baseurl: "/owncloud-quickstart/"
url: "http://schwingle.github.io"


