# Site settings
title: ownCloud Quickstart
description: Quickstart for Installing and Configuring ownCloud
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist
baseurl: "/owncloud-quickstart/"
url: "http://schwingle.github.io/"
