# Site settings
title: ownCloud Quickstart
description: Get Up and Running with ownCloud
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
baseurl: "/owncloud-quickstart/"
url: "http://schwingle.github.io/"
