# Site settings
title: ownCloud Quickstart
description: Get Up and Running with ownCloud
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/owncloud-quickstart/"
url: "http://schwingle.github.io/"
